AppBundle\Entity\ApiUser:
  attributes:
    username:
      groups: ['user']
    email:
      groups: ['user']
    addresses:
      groups: ['user']

AppBundle\Entity\MenuItem:
  attributes:
    offers:
      groups: ['restaurant']
